### ISSUE TITLE
Error when filtering cities in some states

### ISSUE THREAD

**Issue by eduardocorrearaujo** [AlertaDengue/epi-scanner#43]
For some states, such as RJ and ES, the result for a specific city is not visible. The code forces the default city. 

Maybe the code is not finding the result in the table saved with the parameters computed (my hypothesis) 

I also noticed that the screen to filter is different for the states working and not working.

Example: 

- RJ (not working)
<img width="258" alt="Captura de Tela 2024-04-05 às 14 50 46" src="https://github.com/AlertaDengue/epi-scanner/assets/65051489/a738253b-78d4-4a2f-a27e-820ee15cae54">

- MG (working)
-
<img width="580" alt="Captura de Tela 2024-04-05 às 14 51 19" src="https://github.com/AlertaDengue/epi-scanner/assets/65051489/338f0c8d-7384-43f3-89f6-80b94edb4f75">

**Comment by eduardocorrearaujo** [comment]
@luabida percebi que para MG o dashboard está carregando apenas o primeiro gráfico. Isso está relacionado com alguma latencia no acesso aos dados?

**Comment by luabida** [comment]
@eduardocorrearaujo para qual cidade exatamente? aqui parece tudo ok:

![image](https://github.com/user-attachments/assets/4a725751-5fea-43de-8401-769dbe819ff1)
![image](https://github.com/user-attachments/assets/ef47f16d-f49d-4309-8cb2-5e04c370fc7f)

**Comment by eduardocorrearaujo** [comment]
justamente para BH não estava carregando, o problema deve ser na minha conexão então (amém kkkk)
