### ISSUE TITLE
Update table

### ISSUE THREAD

**Issue by eduardocorrearaujo** [AlertaDengue/epi-scanner#46]
I was thinking about updating the table of the parameters. By now, it is: 
![Captura de Tela 2024-05-21 às 11 13 44](https://github.com/AlertaDengue/epi-scanner/assets/65051489/c8a2bea4-ea53-4dc4-a09e-cc3d7751452a)

My purpose is to update it for: 

![Captura de Tela 2024-05-21 às 11 14 45](https://github.com/AlertaDengue/epi-scanner/assets/65051489/5a9cfdda-13e1-4b2b-bdeb-93f4053b4010)

What are your thoughts about it, @fccoelho?

**Comment by fccoelho** [comment]
I suggest changing the last two columns names to `start week` and `end week` , respectively.
I would also add a column for the duration, since now it is not trivial to calculate, by simply subtracting SW from EW.

**Comment by eduardocorrearaujo** [comment]
Solved in PR #47
