### ISSUE TITLE
Update order of elements in the dashboard 

### ISSUE THREAD

**Issue by eduardocorrearaujo** [AlertaDengue/epi-scanner#52]
@fccoelho I think it would be better to show the select box of the year after the table with the parameters and immediately before the line plot.

<img width="445" alt="Captura de Tela 2024-11-04 às 15 17 55" src="https://github.com/user-attachments/assets/2d0aa477-7170-4a3a-80a3-0ce73dae8109">

What are your thoughts about it? Can I create a PR?

**Comment by fccoelho** [comment]
I agree, please go ahead.
